openapi: 3.0.3
info:
  title: Fullstack Challenge - Dictionary API
  description: API para consulta de definições de palavras e gerenciamento de favoritos e histórico.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Servidor local de desenvolvimento

paths:
  /:
    get:
      summary: Retorna uma mensagem de boas-vindas
      responses:
        '200':
          description: Mensagem de boas-vindas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Fullstack Challenge 🏅 - Dictionary

  /user/me:
    get:
      summary: Retorna informações do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Informações do usuário
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    example: "1234567890abcdef"
                  UserName:
                    type: string
                    example: "john_doe"
                  Email:
                    type: string
                    example: "john.doe@example.com"
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found

  /user/me/history:
    get:
      summary: Retorna o histórico de palavras do usuário autenticado
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Histórico de palavras do usuário
          content:
            application/json:
              schema:
                type: object
                properties:
                  Results:
                    type: array
                    items:
                      type: string
                  TotalDocs:
                    type: integer
                  Page:
                    type: integer
                  TotalPages:
                    type: integer
                  HasNext:
                    type: boolean
                  HasPrev:
                    type: boolean
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /user/me/favorites:
    get:
      summary: Retorna os favoritos do usuário autenticado
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Favoritos do usuário
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /entries/en:
    get:
      summary: Retorna palavras de acordo com os critérios de pesquisa
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
            example: "example"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Palavras encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /entries/en/{word}:
    get:
      summary: Retorna a definição de uma palavra
      parameters:
        - name: word
          in: path
          required: true
          schema:
            type: string
            example: "example"
      responses:
        '200':
          description: Informação da palavra
          content:
            application/json:
              schema:
                type: object
                properties:
                  word:
                    type: string
                    example: "example"
                  definition:
                    type: string
                    example: "A representative example"
        '404':
          description: Palavra não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Word not found
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /entries/en/{word}/favorite:
    post:
      summary: Adiciona uma palavra aos favoritos do usuário
      parameters:
        - name: word
          in: path
          required: true
          schema:
            type: string
            example: "example"
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Palavra adicionada aos favoritos
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /entries/en/{word}/unfavorite:
    delete:
      summary: Remove uma palavra dos favoritos do usuário
      parameters:
        - name: word
          in: path
          required: true
          schema:
            type: string
            example: "example"
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Palavra removida dos favoritos
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
